### ISSUE TITLE
question/maybe helpful feature

### ISSUE THREAD

**Issue by ninja542** [snolflake/graphs-and-tracks#85]
I think it would be more helpful for students if the previous run graph would stay when you're changing the initial velocity/position so you can see how it would change the graph

Another thing I would like to ask is if you used SVG or Canvas? I inspected element and saw svg, but would like to clarify how you made the animations.

I'm interested in building some physics simulations, but I was planning on using vue.js and d3.js, and I'm not quite sure what to use for the graphics, SVG or Canvas. 

Thank you

**Comment by bykbtzr** [comment]
Canvas is much faster but there's no way to handle interactions without using yet another library, not to mention the several constructs (lines, circles, arcs, ...) the SVG API has to offer. Using SVG has a cost in performance but I'd say that it pays off in every other aspect.

About Angular 2 I agree that was a very poor choice, most of performance issues I had was due to some misuse of the framework and picking it is a bit overkill for a simple project like this. If I could go back I would indeed pick vue.js over ng2 since it's much cleaner and [faster](https://swizec.com/blog/animating-svg-nodes-react-preact-inferno-vue/swizec/7311), or maybe even React Native so we could make an hybrid app and distribute it on mobile platforms to reach more of our target audience which are students.

>I think it would be more helpful for students if the previous run graph would stay when you're changing the initial velocity/position so you can see how it would change the graph

Maybe @davidtro can explain it better but I if remember correctly the idea of cleaning the graph on almost every change is to encourage the  student to learn to calculate (instead of just visualizing instantaneously) how his changes on the variables' values affect the graph.

**Comment by ninja542** [comment]
Thank you so much for the answer, this will definitely help me in the future!

Do you think the time required to learn React Native is worth it, or is optimizing the website for mobile devices (or tablets) a better use of time? (I heard React takes a while to learn, while vue.js so far seems relatively okay in terms of difficulty of learning)

**Comment by bykbtzr** [comment]
@ninja542 In our case the app is already optimized to run on mobile browsers but distributing the app this way still have several limitations. Using something like React Native would allow us to put it on Google's Play Store and Apple's App Store for example, so in the end it only comes down to how important is the mobile platform for your app, if it will be used mostly on the desktop then vue.js with mobile optimizations would be perfectly fine.

I'm glad to be of any help, If there's any more questions please fell free to ask.

**Comment by ninja542** [comment]
I'm going to close this issue, and thank you a lot, I really appreciate that you took the time to answer my questions.
